[package]
name = "aarch64-qemu"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Percore examples for AArch64 QEMU"
authors = ["Andrew Walbran <qwandor@google.com>"]
repository = "https://github.com/google/percore"
publish = false

[dependencies]
buddy_system_allocator = { version = "0.13.0", default-features = false, features = [
  "alloc",
  "use_spin",
] }
spin = { version = "0.12.0", default-features = false, features = [
  "lazy",
  "once",
  "spin_mutex",
] }
arm-sysregs = { version = "0.4.0", features = ["el1"] }
aarch64-rt = "0.4.3"
aarch64-paging = { version = "0.12.1", default-features = false }
arm-pl011-uart = "0.5.0"
smccc = "0.2.3"
percore = { path = "../..", features = ["derive"] }

[[bin]]
name = "boxed_slice"
path = "src/boxed_slice.rs"

[[bin]]
name = "static_array"
path = "src/static_array.rs"

[[bin]]
name = "macro"
path = "src/macro.rs"
